### PR TITLE
Nicer FreeBSD image :)

### PR DESCRIPTION
**Pull request by palsmo**
just my opinion, merge if you like.

### CODE REVIEW

**Comment by Doctor-love** [comment]
Not bad! Need to crop it to 600x1080 though. Also do you know the license of the picture?

**Comment by palsmo** [comment]
Jag har croppat bilden till 600x1080 och lagt till licens (CC BY-NC 2.0).

**Comment by palsmo** [comment]
Så här ser sidan ut.
freebsd_slide

**Comment by Doctor-love** [comment]
Nice work! I'm however afraid I can't use this image - it's licensed under Creative Commons NonCommercial, which restricts usage. As the README says, I've tried to only include assets licensed under CC0, CC BY and CC BY-SA, which doesn't impose usage restrictions.

If you find another nice FreeBSD image under a more permissive license, please update the PR! :-)

**Pull request closed without merging**
